// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package game_proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GamePacket struct {
	_tab flatbuffers.Table
}

func GetRootAsGamePacket(buf []byte, offset flatbuffers.UOffsetT) *GamePacket {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GamePacket{}
	x.Init(buf, n+offset)
	return x
}

func FinishGamePacketBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGamePacket(buf []byte, offset flatbuffers.UOffsetT) *GamePacket {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GamePacket{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGamePacketBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GamePacket) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GamePacket) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GamePacket) BodyType() GameMessage {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return GameMessage(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *GamePacket) MutateBodyType(n GameMessage) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *GamePacket) Body(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func GamePacketStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GamePacketAddBodyType(builder *flatbuffers.Builder, bodyType GameMessage) {
	builder.PrependByteSlot(0, byte(bodyType), 0)
}
func GamePacketAddBody(builder *flatbuffers.Builder, body flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(body), 0)
}
func GamePacketEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
