// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package game_proto

import "strconv"

type GameMessage byte

const (
	GameMessageNONE            GameMessage = 0
	GameMessagePlayerMove      GameMessage = 1
	GameMessagePlayerShoot     GameMessage = 2
	GameMessageGameStateUpdate GameMessage = 3
)

var EnumNamesGameMessage = map[GameMessage]string{
	GameMessageNONE:            "NONE",
	GameMessagePlayerMove:      "PlayerMove",
	GameMessagePlayerShoot:     "PlayerShoot",
	GameMessageGameStateUpdate: "GameStateUpdate",
}

var EnumValuesGameMessage = map[string]GameMessage{
	"NONE":            GameMessageNONE,
	"PlayerMove":      GameMessagePlayerMove,
	"PlayerShoot":     GameMessagePlayerShoot,
	"GameStateUpdate": GameMessageGameStateUpdate,
}

func (v GameMessage) String() string {
	if s, ok := EnumNamesGameMessage[v]; ok {
		return s
	}
	return "GameMessage(" + strconv.FormatInt(int64(v), 10) + ")"
}
