// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package game_proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GameEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsGameEvent(buf []byte, offset flatbuffers.UOffsetT) *GameEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GameEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishGameEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGameEvent(buf []byte, offset flatbuffers.UOffsetT) *GameEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GameEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGameEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GameEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GameEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GameEvent) EventType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GameEvent) MutateEventType(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *GameEvent) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *GameEvent) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GameEvent) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GameEvent) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func GameEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GameEventAddEventType(builder *flatbuffers.Builder, eventType byte) {
	builder.PrependByteSlot(0, eventType, 0)
}
func GameEventAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(data), 0)
}
func GameEventStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func GameEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
