// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package game_proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PlayerShoot struct {
	_tab flatbuffers.Table
}

func GetRootAsPlayerShoot(buf []byte, offset flatbuffers.UOffsetT) *PlayerShoot {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlayerShoot{}
	x.Init(buf, n+offset)
	return x
}

func FinishPlayerShootBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPlayerShoot(buf []byte, offset flatbuffers.UOffsetT) *PlayerShoot {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PlayerShoot{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPlayerShootBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PlayerShoot) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlayerShoot) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlayerShoot) WeaponType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlayerShoot) MutateWeaponType(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *PlayerShoot) AimX() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PlayerShoot) MutateAimX(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *PlayerShoot) AimY() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PlayerShoot) MutateAimY(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *PlayerShoot) Power() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PlayerShoot) MutatePower(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func (rcv *PlayerShoot) Timestamp() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlayerShoot) MutateTimestamp(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func PlayerShootStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func PlayerShootAddWeaponType(builder *flatbuffers.Builder, weaponType byte) {
	builder.PrependByteSlot(0, weaponType, 0)
}
func PlayerShootAddAimX(builder *flatbuffers.Builder, aimX float32) {
	builder.PrependFloat32Slot(1, aimX, 0.0)
}
func PlayerShootAddAimY(builder *flatbuffers.Builder, aimY float32) {
	builder.PrependFloat32Slot(2, aimY, 0.0)
}
func PlayerShootAddPower(builder *flatbuffers.Builder, power float32) {
	builder.PrependFloat32Slot(3, power, 0.0)
}
func PlayerShootAddTimestamp(builder *flatbuffers.Builder, timestamp uint64) {
	builder.PrependUint64Slot(4, timestamp, 0)
}
func PlayerShootEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
