// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package game_proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PlayerMove struct {
	_tab flatbuffers.Table
}

func GetRootAsPlayerMove(buf []byte, offset flatbuffers.UOffsetT) *PlayerMove {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlayerMove{}
	x.Init(buf, n+offset)
	return x
}

func FinishPlayerMoveBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPlayerMove(buf []byte, offset flatbuffers.UOffsetT) *PlayerMove {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PlayerMove{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPlayerMoveBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PlayerMove) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlayerMove) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlayerMove) PosX() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PlayerMove) MutatePosX(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func (rcv *PlayerMove) PosY() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PlayerMove) MutatePosY(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *PlayerMove) VelX() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PlayerMove) MutateVelX(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *PlayerMove) VelY() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PlayerMove) MutateVelY(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func (rcv *PlayerMove) Timestamp() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlayerMove) MutateTimestamp(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func PlayerMoveStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func PlayerMoveAddPosX(builder *flatbuffers.Builder, posX float32) {
	builder.PrependFloat32Slot(0, posX, 0.0)
}
func PlayerMoveAddPosY(builder *flatbuffers.Builder, posY float32) {
	builder.PrependFloat32Slot(1, posY, 0.0)
}
func PlayerMoveAddVelX(builder *flatbuffers.Builder, velX float32) {
	builder.PrependFloat32Slot(2, velX, 0.0)
}
func PlayerMoveAddVelY(builder *flatbuffers.Builder, velY float32) {
	builder.PrependFloat32Slot(3, velY, 0.0)
}
func PlayerMoveAddTimestamp(builder *flatbuffers.Builder, timestamp uint64) {
	builder.PrependUint64Slot(4, timestamp, 0)
}
func PlayerMoveEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
