// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package game_proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PlayerState struct {
	_tab flatbuffers.Table
}

func GetRootAsPlayerState(buf []byte, offset flatbuffers.UOffsetT) *PlayerState {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlayerState{}
	x.Init(buf, n+offset)
	return x
}

func FinishPlayerStateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPlayerState(buf []byte, offset flatbuffers.UOffsetT) *PlayerState {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PlayerState{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPlayerStateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PlayerState) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlayerState) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlayerState) Uid() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlayerState) MutateUid(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *PlayerState) PosX() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PlayerState) MutatePosX(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *PlayerState) PosY() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PlayerState) MutatePosY(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *PlayerState) Health() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlayerState) MutateHealth(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *PlayerState) Buffs(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *PlayerState) BuffsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PlayerState) BuffsBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PlayerState) MutateBuffs(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func PlayerStateStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func PlayerStateAddUid(builder *flatbuffers.Builder, uid uint64) {
	builder.PrependUint64Slot(0, uid, 0)
}
func PlayerStateAddPosX(builder *flatbuffers.Builder, posX float32) {
	builder.PrependFloat32Slot(1, posX, 0.0)
}
func PlayerStateAddPosY(builder *flatbuffers.Builder, posY float32) {
	builder.PrependFloat32Slot(2, posY, 0.0)
}
func PlayerStateAddHealth(builder *flatbuffers.Builder, health uint32) {
	builder.PrependUint32Slot(3, health, 0)
}
func PlayerStateAddBuffs(builder *flatbuffers.Builder, buffs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(buffs), 0)
}
func PlayerStateStartBuffsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func PlayerStateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
