// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package game_proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ProjectileState struct {
	_tab flatbuffers.Table
}

func GetRootAsProjectileState(buf []byte, offset flatbuffers.UOffsetT) *ProjectileState {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ProjectileState{}
	x.Init(buf, n+offset)
	return x
}

func FinishProjectileStateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsProjectileState(buf []byte, offset flatbuffers.UOffsetT) *ProjectileState {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ProjectileState{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedProjectileStateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ProjectileState) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ProjectileState) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ProjectileState) Id() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ProjectileState) MutateId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *ProjectileState) OwnerUid() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ProjectileState) MutateOwnerUid(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *ProjectileState) PosX() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *ProjectileState) MutatePosX(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *ProjectileState) PosY() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *ProjectileState) MutatePosY(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func (rcv *ProjectileState) VelX() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *ProjectileState) MutateVelX(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func (rcv *ProjectileState) VelY() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *ProjectileState) MutateVelY(n float32) bool {
	return rcv._tab.MutateFloat32Slot(14, n)
}

func (rcv *ProjectileState) ProjType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ProjectileState) MutateProjType(n byte) bool {
	return rcv._tab.MutateByteSlot(16, n)
}

func ProjectileStateStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func ProjectileStateAddId(builder *flatbuffers.Builder, id uint64) {
	builder.PrependUint64Slot(0, id, 0)
}
func ProjectileStateAddOwnerUid(builder *flatbuffers.Builder, ownerUid uint64) {
	builder.PrependUint64Slot(1, ownerUid, 0)
}
func ProjectileStateAddPosX(builder *flatbuffers.Builder, posX float32) {
	builder.PrependFloat32Slot(2, posX, 0.0)
}
func ProjectileStateAddPosY(builder *flatbuffers.Builder, posY float32) {
	builder.PrependFloat32Slot(3, posY, 0.0)
}
func ProjectileStateAddVelX(builder *flatbuffers.Builder, velX float32) {
	builder.PrependFloat32Slot(4, velX, 0.0)
}
func ProjectileStateAddVelY(builder *flatbuffers.Builder, velY float32) {
	builder.PrependFloat32Slot(5, velY, 0.0)
}
func ProjectileStateAddProjType(builder *flatbuffers.Builder, projType byte) {
	builder.PrependByteSlot(6, projType, 0)
}
func ProjectileStateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
