// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package net_proto

import "strconv"

type AnyMessage byte

const (
	AnyMessageNONE             AnyMessage = 0
	AnyMessageAuthRequest      AnyMessage = 1
	AnyMessageAuthResponse     AnyMessage = 2
	AnyMessageJoinRoom         AnyMessage = 3
	AnyMessageJoinRoomResponse AnyMessage = 4
	AnyMessageGameData         AnyMessage = 5
	AnyMessageHeartbeat        AnyMessage = 6
)

var EnumNamesAnyMessage = map[AnyMessage]string{
	AnyMessageNONE:             "NONE",
	AnyMessageAuthRequest:      "AuthRequest",
	AnyMessageAuthResponse:     "AuthResponse",
	AnyMessageJoinRoom:         "JoinRoom",
	AnyMessageJoinRoomResponse: "JoinRoomResponse",
	AnyMessageGameData:         "GameData",
	AnyMessageHeartbeat:        "Heartbeat",
}

var EnumValuesAnyMessage = map[string]AnyMessage{
	"NONE":             AnyMessageNONE,
	"AuthRequest":      AnyMessageAuthRequest,
	"AuthResponse":     AnyMessageAuthResponse,
	"JoinRoom":         AnyMessageJoinRoom,
	"JoinRoomResponse": AnyMessageJoinRoomResponse,
	"GameData":         AnyMessageGameData,
	"Heartbeat":        AnyMessageHeartbeat,
}

func (v AnyMessage) String() string {
	if s, ok := EnumNamesAnyMessage[v]; ok {
		return s
	}
	return "AnyMessage(" + strconv.FormatInt(int64(v), 10) + ")"
}
