// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package net_proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AuthResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsAuthResponse(buf []byte, offset flatbuffers.UOffsetT) *AuthResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AuthResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishAuthResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAuthResponse(buf []byte, offset flatbuffers.UOffsetT) *AuthResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AuthResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAuthResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AuthResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AuthResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AuthResponse) Success() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *AuthResponse) MutateSuccess(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *AuthResponse) SessionId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AuthResponse) MutateSessionId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *AuthResponse) ErrorMessage() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AuthResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func AuthResponseAddSuccess(builder *flatbuffers.Builder, success bool) {
	builder.PrependBoolSlot(0, success, false)
}
func AuthResponseAddSessionId(builder *flatbuffers.Builder, sessionId uint64) {
	builder.PrependUint64Slot(1, sessionId, 0)
}
func AuthResponseAddErrorMessage(builder *flatbuffers.Builder, errorMessage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(errorMessage), 0)
}
func AuthResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
