// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package net_proto

import "strconv"

type GameMode byte

const (
	GameModeQuickMatch   GameMode = 0
	GameModeSpecificRoom GameMode = 1
)

var EnumNamesGameMode = map[GameMode]string{
	GameModeQuickMatch:   "QuickMatch",
	GameModeSpecificRoom: "SpecificRoom",
}

var EnumValuesGameMode = map[string]GameMode{
	"QuickMatch":   GameModeQuickMatch,
	"SpecificRoom": GameModeSpecificRoom,
}

func (v GameMode) String() string {
	if s, ok := EnumNamesGameMode[v]; ok {
		return s
	}
	return "GameMode(" + strconv.FormatInt(int64(v), 10) + ")"
}
