// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package net_proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Heartbeat struct {
	_tab flatbuffers.Table
}

func GetRootAsHeartbeat(buf []byte, offset flatbuffers.UOffsetT) *Heartbeat {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Heartbeat{}
	x.Init(buf, n+offset)
	return x
}

func FinishHeartbeatBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHeartbeat(buf []byte, offset flatbuffers.UOffsetT) *Heartbeat {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Heartbeat{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHeartbeatBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Heartbeat) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Heartbeat) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Heartbeat) Ping() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Heartbeat) MutatePing(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func HeartbeatStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func HeartbeatAddPing(builder *flatbuffers.Builder, ping uint64) {
	builder.PrependUint64Slot(0, ping, 0)
}
func HeartbeatEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
