// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package net_proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type JoinRoom struct {
	_tab flatbuffers.Table
}

func GetRootAsJoinRoom(buf []byte, offset flatbuffers.UOffsetT) *JoinRoom {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &JoinRoom{}
	x.Init(buf, n+offset)
	return x
}

func FinishJoinRoomBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsJoinRoom(buf []byte, offset flatbuffers.UOffsetT) *JoinRoom {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &JoinRoom{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedJoinRoomBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *JoinRoom) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *JoinRoom) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *JoinRoom) Mode() GameMode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return GameMode(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *JoinRoom) MutateMode(n GameMode) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *JoinRoom) TargetRoomId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *JoinRoom) MutateTargetRoomId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func JoinRoomStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func JoinRoomAddMode(builder *flatbuffers.Builder, mode GameMode) {
	builder.PrependByteSlot(0, byte(mode), 0)
}
func JoinRoomAddTargetRoomId(builder *flatbuffers.Builder, targetRoomId uint64) {
	builder.PrependUint64Slot(1, targetRoomId, 0)
}
func JoinRoomEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
