// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package net_proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type JoinRoomResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsJoinRoomResponse(buf []byte, offset flatbuffers.UOffsetT) *JoinRoomResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &JoinRoomResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishJoinRoomResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsJoinRoomResponse(buf []byte, offset flatbuffers.UOffsetT) *JoinRoomResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &JoinRoomResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedJoinRoomResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *JoinRoomResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *JoinRoomResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *JoinRoomResponse) Success() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *JoinRoomResponse) MutateSuccess(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *JoinRoomResponse) RoomId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *JoinRoomResponse) MutateRoomId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *JoinRoomResponse) GameServerAddr() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *JoinRoomResponse) ErrorCode() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *JoinRoomResponse) MutateErrorCode(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func JoinRoomResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func JoinRoomResponseAddSuccess(builder *flatbuffers.Builder, success bool) {
	builder.PrependBoolSlot(0, success, false)
}
func JoinRoomResponseAddRoomId(builder *flatbuffers.Builder, roomId uint64) {
	builder.PrependUint64Slot(1, roomId, 0)
}
func JoinRoomResponseAddGameServerAddr(builder *flatbuffers.Builder, gameServerAddr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(gameServerAddr), 0)
}
func JoinRoomResponseAddErrorCode(builder *flatbuffers.Builder, errorCode int32) {
	builder.PrependInt32Slot(3, errorCode, 0)
}
func JoinRoomResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
