// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package net_proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PacketHeader struct {
	_tab flatbuffers.Struct
}

func (rcv *PacketHeader) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PacketHeader) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *PacketHeader) Magic() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *PacketHeader) MutateMagic(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *PacketHeader) Version() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *PacketHeader) MutateVersion(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *PacketHeader) Flags() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(6))
}
func (rcv *PacketHeader) MutateFlags(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(6), n)
}

func (rcv *PacketHeader) SessionId() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *PacketHeader) MutateSessionId(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *PacketHeader) RoomId() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(16))
}
func (rcv *PacketHeader) MutateRoomId(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(16), n)
}

func (rcv *PacketHeader) MsgType() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(24))
}
func (rcv *PacketHeader) MutateMsgType(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(24), n)
}

func (rcv *PacketHeader) Reserved() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(26))
}
func (rcv *PacketHeader) MutateReserved(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(26), n)
}

func (rcv *PacketHeader) Timestamp() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(32))
}
func (rcv *PacketHeader) MutateTimestamp(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(32), n)
}

func CreatePacketHeader(builder *flatbuffers.Builder, magic uint32, version uint16, flags uint16, sessionId uint64, roomId uint64, msgType uint16, reserved uint16, timestamp uint64) flatbuffers.UOffsetT {
	builder.Prep(8, 40)
	builder.PrependUint64(timestamp)
	builder.Pad(4)
	builder.PrependUint16(reserved)
	builder.PrependUint16(msgType)
	builder.PrependUint64(roomId)
	builder.PrependUint64(sessionId)
	builder.PrependUint16(flags)
	builder.PrependUint16(version)
	builder.PrependUint32(magic)
	return builder.Offset()
}
