// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace net_proto
{

public enum AnyMessage : byte
{
  NONE = 0,
  AuthRequest = 1,
  AuthResponse = 2,
  JoinRoom = 3,
  JoinRoomResponse = 4,
  GameData = 5,
  Heartbeat = 6,
};



static public class AnyMessageVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((AnyMessage)typeId)
    {
      case AnyMessage.AuthRequest:
        result = net_proto.AuthRequestVerify.Verify(verifier, tablePos);
        break;
      case AnyMessage.AuthResponse:
        result = net_proto.AuthResponseVerify.Verify(verifier, tablePos);
        break;
      case AnyMessage.JoinRoom:
        result = net_proto.JoinRoomVerify.Verify(verifier, tablePos);
        break;
      case AnyMessage.JoinRoomResponse:
        result = net_proto.JoinRoomResponseVerify.Verify(verifier, tablePos);
        break;
      case AnyMessage.GameData:
        result = net_proto.GameDataVerify.Verify(verifier, tablePos);
        break;
      case AnyMessage.Heartbeat:
        result = net_proto.HeartbeatVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
