// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace net_proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct AuthRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static AuthRequest GetRootAsAuthRequest(ByteBuffer _bb) { return GetRootAsAuthRequest(_bb, new AuthRequest()); }
  public static AuthRequest GetRootAsAuthRequest(ByteBuffer _bb, AuthRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AuthRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Token { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTokenBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetTokenBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetTokenArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<net_proto.AuthRequest> CreateAuthRequest(FlatBufferBuilder builder,
      StringOffset tokenOffset = default(StringOffset)) {
    builder.StartTable(1);
    AuthRequest.AddToken(builder, tokenOffset);
    return AuthRequest.EndAuthRequest(builder);
  }

  public static void StartAuthRequest(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddToken(FlatBufferBuilder builder, StringOffset tokenOffset) { builder.AddOffset(0, tokenOffset.Value, 0); }
  public static Offset<net_proto.AuthRequest> EndAuthRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<net_proto.AuthRequest>(o);
  }
}


static public class AuthRequestVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Token*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
