// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace net_proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct AuthResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static AuthResponse GetRootAsAuthResponse(ByteBuffer _bb) { return GetRootAsAuthResponse(_bb, new AuthResponse()); }
  public static AuthResponse GetRootAsAuthResponse(ByteBuffer _bb, AuthResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AuthResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Success { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public ulong SessionId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public string ErrorMessage { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetErrorMessageBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetErrorMessageBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetErrorMessageArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<net_proto.AuthResponse> CreateAuthResponse(FlatBufferBuilder builder,
      bool success = false,
      ulong session_id = 0,
      StringOffset error_messageOffset = default(StringOffset)) {
    builder.StartTable(3);
    AuthResponse.AddSessionId(builder, session_id);
    AuthResponse.AddErrorMessage(builder, error_messageOffset);
    AuthResponse.AddSuccess(builder, success);
    return AuthResponse.EndAuthResponse(builder);
  }

  public static void StartAuthResponse(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddSuccess(FlatBufferBuilder builder, bool success) { builder.AddBool(0, success, false); }
  public static void AddSessionId(FlatBufferBuilder builder, ulong sessionId) { builder.AddUlong(1, sessionId, 0); }
  public static void AddErrorMessage(FlatBufferBuilder builder, StringOffset errorMessageOffset) { builder.AddOffset(2, errorMessageOffset.Value, 0); }
  public static Offset<net_proto.AuthResponse> EndAuthResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<net_proto.AuthResponse>(o);
  }
}


static public class AuthResponseVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Success*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*SessionId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyString(tablePos, 8 /*ErrorMessage*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
