// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace net_proto
{

public enum GameMode : byte
{
  QuickMatch = 0,
  SpecificRoom = 1,
};


}
