// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace net_proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Heartbeat : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static Heartbeat GetRootAsHeartbeat(ByteBuffer _bb) { return GetRootAsHeartbeat(_bb, new Heartbeat()); }
  public static Heartbeat GetRootAsHeartbeat(ByteBuffer _bb, Heartbeat obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Heartbeat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Ping { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<net_proto.Heartbeat> CreateHeartbeat(FlatBufferBuilder builder,
      ulong ping = 0) {
    builder.StartTable(1);
    Heartbeat.AddPing(builder, ping);
    return Heartbeat.EndHeartbeat(builder);
  }

  public static void StartHeartbeat(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPing(FlatBufferBuilder builder, ulong ping) { builder.AddUlong(0, ping, 0); }
  public static Offset<net_proto.Heartbeat> EndHeartbeat(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<net_proto.Heartbeat>(o);
  }
}


static public class HeartbeatVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Ping*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
