// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace net_proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct JoinRoom : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static JoinRoom GetRootAsJoinRoom(ByteBuffer _bb) { return GetRootAsJoinRoom(_bb, new JoinRoom()); }
  public static JoinRoom GetRootAsJoinRoom(ByteBuffer _bb, JoinRoom obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public JoinRoom __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public net_proto.GameMode Mode { get { int o = __p.__offset(4); return o != 0 ? (net_proto.GameMode)__p.bb.Get(o + __p.bb_pos) : net_proto.GameMode.QuickMatch; } }
  public ulong TargetRoomId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<net_proto.JoinRoom> CreateJoinRoom(FlatBufferBuilder builder,
      net_proto.GameMode mode = net_proto.GameMode.QuickMatch,
      ulong target_room_id = 0) {
    builder.StartTable(2);
    JoinRoom.AddTargetRoomId(builder, target_room_id);
    JoinRoom.AddMode(builder, mode);
    return JoinRoom.EndJoinRoom(builder);
  }

  public static void StartJoinRoom(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddMode(FlatBufferBuilder builder, net_proto.GameMode mode) { builder.AddByte(0, (byte)mode, 0); }
  public static void AddTargetRoomId(FlatBufferBuilder builder, ulong targetRoomId) { builder.AddUlong(1, targetRoomId, 0); }
  public static Offset<net_proto.JoinRoom> EndJoinRoom(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<net_proto.JoinRoom>(o);
  }
}


static public class JoinRoomVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Mode*/, 1 /*net_proto.GameMode*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*TargetRoomId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
