// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace net_proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct JoinRoomResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static JoinRoomResponse GetRootAsJoinRoomResponse(ByteBuffer _bb) { return GetRootAsJoinRoomResponse(_bb, new JoinRoomResponse()); }
  public static JoinRoomResponse GetRootAsJoinRoomResponse(ByteBuffer _bb, JoinRoomResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public JoinRoomResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Success { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public ulong RoomId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public string GameServerAddr { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetGameServerAddrBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetGameServerAddrBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetGameServerAddrArray() { return __p.__vector_as_array<byte>(8); }
  public int ErrorCode { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<net_proto.JoinRoomResponse> CreateJoinRoomResponse(FlatBufferBuilder builder,
      bool success = false,
      ulong room_id = 0,
      StringOffset game_server_addrOffset = default(StringOffset),
      int error_code = 0) {
    builder.StartTable(4);
    JoinRoomResponse.AddRoomId(builder, room_id);
    JoinRoomResponse.AddErrorCode(builder, error_code);
    JoinRoomResponse.AddGameServerAddr(builder, game_server_addrOffset);
    JoinRoomResponse.AddSuccess(builder, success);
    return JoinRoomResponse.EndJoinRoomResponse(builder);
  }

  public static void StartJoinRoomResponse(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddSuccess(FlatBufferBuilder builder, bool success) { builder.AddBool(0, success, false); }
  public static void AddRoomId(FlatBufferBuilder builder, ulong roomId) { builder.AddUlong(1, roomId, 0); }
  public static void AddGameServerAddr(FlatBufferBuilder builder, StringOffset gameServerAddrOffset) { builder.AddOffset(2, gameServerAddrOffset.Value, 0); }
  public static void AddErrorCode(FlatBufferBuilder builder, int errorCode) { builder.AddInt(3, errorCode, 0); }
  public static Offset<net_proto.JoinRoomResponse> EndJoinRoomResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<net_proto.JoinRoomResponse>(o);
  }
}


static public class JoinRoomResponseVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Success*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*RoomId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyString(tablePos, 8 /*GameServerAddr*/, false)
      && verifier.VerifyField(tablePos, 10 /*ErrorCode*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
