// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace net_proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Message : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static Message GetRootAsMessage(ByteBuffer _bb) { return GetRootAsMessage(_bb, new Message()); }
  public static Message GetRootAsMessage(ByteBuffer _bb, Message obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyMessage(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, MessageVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Message __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public net_proto.PacketHeader? Header { get { int o = __p.__offset(4); return o != 0 ? (net_proto.PacketHeader?)(new net_proto.PacketHeader()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public net_proto.AnyMessage BodyType { get { int o = __p.__offset(6); return o != 0 ? (net_proto.AnyMessage)__p.bb.Get(o + __p.bb_pos) : net_proto.AnyMessage.NONE; } }
  public TTable? Body<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(8); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public net_proto.AuthRequest BodyAsAuthRequest() { return Body<net_proto.AuthRequest>().Value; }
  public net_proto.AuthResponse BodyAsAuthResponse() { return Body<net_proto.AuthResponse>().Value; }
  public net_proto.JoinRoom BodyAsJoinRoom() { return Body<net_proto.JoinRoom>().Value; }
  public net_proto.JoinRoomResponse BodyAsJoinRoomResponse() { return Body<net_proto.JoinRoomResponse>().Value; }
  public net_proto.GameData BodyAsGameData() { return Body<net_proto.GameData>().Value; }
  public net_proto.Heartbeat BodyAsHeartbeat() { return Body<net_proto.Heartbeat>().Value; }

  public static void StartMessage(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddHeader(FlatBufferBuilder builder, Offset<net_proto.PacketHeader> headerOffset) { builder.AddStruct(0, headerOffset.Value, 0); }
  public static void AddBodyType(FlatBufferBuilder builder, net_proto.AnyMessage bodyType) { builder.AddByte(1, (byte)bodyType, 0); }
  public static void AddBody(FlatBufferBuilder builder, int bodyOffset) { builder.AddOffset(2, bodyOffset, 0); }
  public static Offset<net_proto.Message> EndMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<net_proto.Message>(o);
  }
  public static void FinishMessageBuffer(FlatBufferBuilder builder, Offset<net_proto.Message> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedMessageBuffer(FlatBufferBuilder builder, Offset<net_proto.Message> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class MessageVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Header*/, 40 /*net_proto.PacketHeader*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*BodyType*/, 1 /*net_proto.AnyMessage*/, 1, false)
      && verifier.VerifyUnion(tablePos, 6, 8 /*Body*/, net_proto.AnyMessageVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
