// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace net_proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PacketHeader : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public PacketHeader __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Magic { get { return __p.bb.GetUint(__p.bb_pos + 0); } }
  public ushort Version { get { return __p.bb.GetUshort(__p.bb_pos + 4); } }
  public ushort Flags { get { return __p.bb.GetUshort(__p.bb_pos + 6); } }
  public ulong SessionId { get { return __p.bb.GetUlong(__p.bb_pos + 8); } }
  public ulong RoomId { get { return __p.bb.GetUlong(__p.bb_pos + 16); } }
  public ushort MsgType { get { return __p.bb.GetUshort(__p.bb_pos + 24); } }
  public ushort Reserved { get { return __p.bb.GetUshort(__p.bb_pos + 26); } }
  public ulong Timestamp { get { return __p.bb.GetUlong(__p.bb_pos + 32); } }

  public static Offset<net_proto.PacketHeader> CreatePacketHeader(FlatBufferBuilder builder, uint Magic, ushort Version, ushort Flags, ulong SessionId, ulong RoomId, ushort MsgType, ushort Reserved, ulong Timestamp) {
    builder.Prep(8, 40);
    builder.PutUlong(Timestamp);
    builder.Pad(4);
    builder.PutUshort(Reserved);
    builder.PutUshort(MsgType);
    builder.PutUlong(RoomId);
    builder.PutUlong(SessionId);
    builder.PutUshort(Flags);
    builder.PutUshort(Version);
    builder.PutUint(Magic);
    return new Offset<net_proto.PacketHeader>(builder.Offset);
  }
}


}
