// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace game_proto
{

public enum GameMessage : byte
{
  NONE = 0,
  PlayerMove = 1,
  PlayerShoot = 2,
  GameStateUpdate = 3,
};



static public class GameMessageVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((GameMessage)typeId)
    {
      case GameMessage.PlayerMove:
        result = game_proto.PlayerMoveVerify.Verify(verifier, tablePos);
        break;
      case GameMessage.PlayerShoot:
        result = game_proto.PlayerShootVerify.Verify(verifier, tablePos);
        break;
      case GameMessage.GameStateUpdate:
        result = game_proto.GameStateUpdateVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
