// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace game_proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GamePacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static GamePacket GetRootAsGamePacket(ByteBuffer _bb) { return GetRootAsGamePacket(_bb, new GamePacket()); }
  public static GamePacket GetRootAsGamePacket(ByteBuffer _bb, GamePacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyGamePacket(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, GamePacketVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GamePacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public game_proto.GameMessage BodyType { get { int o = __p.__offset(4); return o != 0 ? (game_proto.GameMessage)__p.bb.Get(o + __p.bb_pos) : game_proto.GameMessage.NONE; } }
  public TTable? Body<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public game_proto.PlayerMove BodyAsPlayerMove() { return Body<game_proto.PlayerMove>().Value; }
  public game_proto.PlayerShoot BodyAsPlayerShoot() { return Body<game_proto.PlayerShoot>().Value; }
  public game_proto.GameStateUpdate BodyAsGameStateUpdate() { return Body<game_proto.GameStateUpdate>().Value; }

  public static Offset<game_proto.GamePacket> CreateGamePacket(FlatBufferBuilder builder,
      game_proto.GameMessage body_type = game_proto.GameMessage.NONE,
      int bodyOffset = 0) {
    builder.StartTable(2);
    GamePacket.AddBody(builder, bodyOffset);
    GamePacket.AddBodyType(builder, body_type);
    return GamePacket.EndGamePacket(builder);
  }

  public static void StartGamePacket(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddBodyType(FlatBufferBuilder builder, game_proto.GameMessage bodyType) { builder.AddByte(0, (byte)bodyType, 0); }
  public static void AddBody(FlatBufferBuilder builder, int bodyOffset) { builder.AddOffset(1, bodyOffset, 0); }
  public static Offset<game_proto.GamePacket> EndGamePacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<game_proto.GamePacket>(o);
  }
  public static void FinishGamePacketBuffer(FlatBufferBuilder builder, Offset<game_proto.GamePacket> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedGamePacketBuffer(FlatBufferBuilder builder, Offset<game_proto.GamePacket> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class GamePacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*BodyType*/, 1 /*game_proto.GameMessage*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*Body*/, game_proto.GameMessageVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
