// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace game_proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GameStateUpdate : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static GameStateUpdate GetRootAsGameStateUpdate(ByteBuffer _bb) { return GetRootAsGameStateUpdate(_bb, new GameStateUpdate()); }
  public static GameStateUpdate GetRootAsGameStateUpdate(ByteBuffer _bb, GameStateUpdate obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GameStateUpdate __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public game_proto.PlayerState? Players(int j) { int o = __p.__offset(4); return o != 0 ? (game_proto.PlayerState?)(new game_proto.PlayerState()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int PlayersLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public game_proto.ProjectileState? Projectiles(int j) { int o = __p.__offset(6); return o != 0 ? (game_proto.ProjectileState?)(new game_proto.ProjectileState()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ProjectilesLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public game_proto.GameEvent? Events(int j) { int o = __p.__offset(8); return o != 0 ? (game_proto.GameEvent?)(new game_proto.GameEvent()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int EventsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ulong Timestamp { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<game_proto.GameStateUpdate> CreateGameStateUpdate(FlatBufferBuilder builder,
      VectorOffset playersOffset = default(VectorOffset),
      VectorOffset projectilesOffset = default(VectorOffset),
      VectorOffset eventsOffset = default(VectorOffset),
      ulong timestamp = 0) {
    builder.StartTable(4);
    GameStateUpdate.AddTimestamp(builder, timestamp);
    GameStateUpdate.AddEvents(builder, eventsOffset);
    GameStateUpdate.AddProjectiles(builder, projectilesOffset);
    GameStateUpdate.AddPlayers(builder, playersOffset);
    return GameStateUpdate.EndGameStateUpdate(builder);
  }

  public static void StartGameStateUpdate(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddPlayers(FlatBufferBuilder builder, VectorOffset playersOffset) { builder.AddOffset(0, playersOffset.Value, 0); }
  public static VectorOffset CreatePlayersVector(FlatBufferBuilder builder, Offset<game_proto.PlayerState>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreatePlayersVectorBlock(FlatBufferBuilder builder, Offset<game_proto.PlayerState>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePlayersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<game_proto.PlayerState>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePlayersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<game_proto.PlayerState>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPlayersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddProjectiles(FlatBufferBuilder builder, VectorOffset projectilesOffset) { builder.AddOffset(1, projectilesOffset.Value, 0); }
  public static VectorOffset CreateProjectilesVector(FlatBufferBuilder builder, Offset<game_proto.ProjectileState>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateProjectilesVectorBlock(FlatBufferBuilder builder, Offset<game_proto.ProjectileState>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateProjectilesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<game_proto.ProjectileState>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateProjectilesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<game_proto.ProjectileState>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartProjectilesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddEvents(FlatBufferBuilder builder, VectorOffset eventsOffset) { builder.AddOffset(2, eventsOffset.Value, 0); }
  public static VectorOffset CreateEventsVector(FlatBufferBuilder builder, Offset<game_proto.GameEvent>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateEventsVectorBlock(FlatBufferBuilder builder, Offset<game_proto.GameEvent>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEventsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<game_proto.GameEvent>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEventsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<game_proto.GameEvent>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartEventsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddTimestamp(FlatBufferBuilder builder, ulong timestamp) { builder.AddUlong(3, timestamp, 0); }
  public static Offset<game_proto.GameStateUpdate> EndGameStateUpdate(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<game_proto.GameStateUpdate>(o);
  }
}


static public class GameStateUpdateVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Players*/, game_proto.PlayerStateVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Projectiles*/, game_proto.ProjectileStateVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*Events*/, game_proto.GameEventVerify.Verify, false)
      && verifier.VerifyField(tablePos, 10 /*Timestamp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
