// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace game_proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PlayerMove : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static PlayerMove GetRootAsPlayerMove(ByteBuffer _bb) { return GetRootAsPlayerMove(_bb, new PlayerMove()); }
  public static PlayerMove GetRootAsPlayerMove(ByteBuffer _bb, PlayerMove obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerMove __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float PosX { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float PosY { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float VelX { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float VelY { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public ulong Timestamp { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<game_proto.PlayerMove> CreatePlayerMove(FlatBufferBuilder builder,
      float pos_x = 0.0f,
      float pos_y = 0.0f,
      float vel_x = 0.0f,
      float vel_y = 0.0f,
      ulong timestamp = 0) {
    builder.StartTable(5);
    PlayerMove.AddTimestamp(builder, timestamp);
    PlayerMove.AddVelY(builder, vel_y);
    PlayerMove.AddVelX(builder, vel_x);
    PlayerMove.AddPosY(builder, pos_y);
    PlayerMove.AddPosX(builder, pos_x);
    return PlayerMove.EndPlayerMove(builder);
  }

  public static void StartPlayerMove(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddPosX(FlatBufferBuilder builder, float posX) { builder.AddFloat(0, posX, 0.0f); }
  public static void AddPosY(FlatBufferBuilder builder, float posY) { builder.AddFloat(1, posY, 0.0f); }
  public static void AddVelX(FlatBufferBuilder builder, float velX) { builder.AddFloat(2, velX, 0.0f); }
  public static void AddVelY(FlatBufferBuilder builder, float velY) { builder.AddFloat(3, velY, 0.0f); }
  public static void AddTimestamp(FlatBufferBuilder builder, ulong timestamp) { builder.AddUlong(4, timestamp, 0); }
  public static Offset<game_proto.PlayerMove> EndPlayerMove(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<game_proto.PlayerMove>(o);
  }
}


static public class PlayerMoveVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PosX*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*PosY*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*VelX*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*VelY*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*Timestamp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
