// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace game_proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PlayerState : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static PlayerState GetRootAsPlayerState(ByteBuffer _bb) { return GetRootAsPlayerState(_bb, new PlayerState()); }
  public static PlayerState GetRootAsPlayerState(ByteBuffer _bb, PlayerState obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerState __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Uid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public float PosX { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float PosY { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public uint Health { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public byte Buffs(int j) { int o = __p.__offset(12); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int BuffsLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBuffsBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetBuffsBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetBuffsArray() { return __p.__vector_as_array<byte>(12); }

  public static Offset<game_proto.PlayerState> CreatePlayerState(FlatBufferBuilder builder,
      ulong uid = 0,
      float pos_x = 0.0f,
      float pos_y = 0.0f,
      uint health = 0,
      VectorOffset buffsOffset = default(VectorOffset)) {
    builder.StartTable(5);
    PlayerState.AddUid(builder, uid);
    PlayerState.AddBuffs(builder, buffsOffset);
    PlayerState.AddHealth(builder, health);
    PlayerState.AddPosY(builder, pos_y);
    PlayerState.AddPosX(builder, pos_x);
    return PlayerState.EndPlayerState(builder);
  }

  public static void StartPlayerState(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddUid(FlatBufferBuilder builder, ulong uid) { builder.AddUlong(0, uid, 0); }
  public static void AddPosX(FlatBufferBuilder builder, float posX) { builder.AddFloat(1, posX, 0.0f); }
  public static void AddPosY(FlatBufferBuilder builder, float posY) { builder.AddFloat(2, posY, 0.0f); }
  public static void AddHealth(FlatBufferBuilder builder, uint health) { builder.AddUint(3, health, 0); }
  public static void AddBuffs(FlatBufferBuilder builder, VectorOffset buffsOffset) { builder.AddOffset(4, buffsOffset.Value, 0); }
  public static VectorOffset CreateBuffsVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateBuffsVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBuffsVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBuffsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartBuffsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<game_proto.PlayerState> EndPlayerState(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<game_proto.PlayerState>(o);
  }
}


static public class PlayerStateVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Uid*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*PosX*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*PosY*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*Health*/, 4 /*uint*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 12 /*Buffs*/, 1 /*byte*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
