// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace game_proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PlayerShoot : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static PlayerShoot GetRootAsPlayerShoot(ByteBuffer _bb) { return GetRootAsPlayerShoot(_bb, new PlayerShoot()); }
  public static PlayerShoot GetRootAsPlayerShoot(ByteBuffer _bb, PlayerShoot obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerShoot __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte WeaponType { get { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public float AimX { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float AimY { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Power { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public ulong Timestamp { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<game_proto.PlayerShoot> CreatePlayerShoot(FlatBufferBuilder builder,
      byte weapon_type = 0,
      float aim_x = 0.0f,
      float aim_y = 0.0f,
      float power = 0.0f,
      ulong timestamp = 0) {
    builder.StartTable(5);
    PlayerShoot.AddTimestamp(builder, timestamp);
    PlayerShoot.AddPower(builder, power);
    PlayerShoot.AddAimY(builder, aim_y);
    PlayerShoot.AddAimX(builder, aim_x);
    PlayerShoot.AddWeaponType(builder, weapon_type);
    return PlayerShoot.EndPlayerShoot(builder);
  }

  public static void StartPlayerShoot(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddWeaponType(FlatBufferBuilder builder, byte weaponType) { builder.AddByte(0, weaponType, 0); }
  public static void AddAimX(FlatBufferBuilder builder, float aimX) { builder.AddFloat(1, aimX, 0.0f); }
  public static void AddAimY(FlatBufferBuilder builder, float aimY) { builder.AddFloat(2, aimY, 0.0f); }
  public static void AddPower(FlatBufferBuilder builder, float power) { builder.AddFloat(3, power, 0.0f); }
  public static void AddTimestamp(FlatBufferBuilder builder, ulong timestamp) { builder.AddUlong(4, timestamp, 0); }
  public static Offset<game_proto.PlayerShoot> EndPlayerShoot(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<game_proto.PlayerShoot>(o);
  }
}


static public class PlayerShootVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*WeaponType*/, 1 /*byte*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*AimX*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*AimY*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*Power*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*Timestamp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
