// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace game_proto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ProjectileState : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ProjectileState GetRootAsProjectileState(ByteBuffer _bb) { return GetRootAsProjectileState(_bb, new ProjectileState()); }
  public static ProjectileState GetRootAsProjectileState(ByteBuffer _bb, ProjectileState obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ProjectileState __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong OwnerUid { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public float PosX { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float PosY { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float VelX { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float VelY { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public byte ProjType { get { int o = __p.__offset(16); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<game_proto.ProjectileState> CreateProjectileState(FlatBufferBuilder builder,
      ulong id = 0,
      ulong owner_uid = 0,
      float pos_x = 0.0f,
      float pos_y = 0.0f,
      float vel_x = 0.0f,
      float vel_y = 0.0f,
      byte proj_type = 0) {
    builder.StartTable(7);
    ProjectileState.AddOwnerUid(builder, owner_uid);
    ProjectileState.AddId(builder, id);
    ProjectileState.AddVelY(builder, vel_y);
    ProjectileState.AddVelX(builder, vel_x);
    ProjectileState.AddPosY(builder, pos_y);
    ProjectileState.AddPosX(builder, pos_x);
    ProjectileState.AddProjType(builder, proj_type);
    return ProjectileState.EndProjectileState(builder);
  }

  public static void StartProjectileState(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddId(FlatBufferBuilder builder, ulong id) { builder.AddUlong(0, id, 0); }
  public static void AddOwnerUid(FlatBufferBuilder builder, ulong ownerUid) { builder.AddUlong(1, ownerUid, 0); }
  public static void AddPosX(FlatBufferBuilder builder, float posX) { builder.AddFloat(2, posX, 0.0f); }
  public static void AddPosY(FlatBufferBuilder builder, float posY) { builder.AddFloat(3, posY, 0.0f); }
  public static void AddVelX(FlatBufferBuilder builder, float velX) { builder.AddFloat(4, velX, 0.0f); }
  public static void AddVelY(FlatBufferBuilder builder, float velY) { builder.AddFloat(5, velY, 0.0f); }
  public static void AddProjType(FlatBufferBuilder builder, byte projType) { builder.AddByte(6, projType, 0); }
  public static Offset<game_proto.ProjectileState> EndProjectileState(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<game_proto.ProjectileState>(o);
  }
}


static public class ProjectileStateVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*OwnerUid*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*PosX*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*PosY*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*VelX*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*VelY*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*ProjType*/, 1 /*byte*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
